### ISSUE TITLE
Add a type checker

### ISSUE THREAD

**Issue by cacay** [apl-cornell/viaduct#21]

**Comment by rolph-recto** [comment]
basic type checking complete as of https://github.com/apl-cornell/viaduct/commit/49447ab5380e4bf3ab3698c891fdb7ebdef46303

This does not include label checking. We want to add a separate pass that does that.

Type information needs to be persisted in AST nodes so that protocol instantiation can correctly infer the types of `recv` statements. Currently instantiation is *not* type-preserving.

**Comment by rolph-recto** [comment]
Label checking (using a constraint solver) complete as of 80189d3af0bb560eaa5114721443a7c0dc078e67
